In [1]:
import pandas
import numpy

In [2]:
data = pandas.read_csv("Airbnb_Data.csv")
df = pandas.DataFrame(data)
df

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,14549287,4.605170,Apartment,Private room,{},1,1.0,Real Bed,flexible,False,...,40.709025,-73.939405,one room bushwick,Williamsburg,0,NaN,https://a0.muscache.com/im/pictures/55162426/6...,11206.0,1.0,1.0
74107,13281809,5.043425,Apartment,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,2.0,Real Bed,moderate,True,...,33.871549,-118.396053,Spacious Hermosa 2 BR on PCH,Hermosa Beach,16,93.0,https://a0.muscache.com/im/pictures/2b86560b-a...,90254,2.0,4.0
74108,18688039,5.220356,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",5,1.0,Real Bed,moderate,True,...,40.706749,-73.942377,Modern 2 Bedroom Apartment in Williamsburg,Williamsburg,43,94.0,https://a0.muscache.com/im/pictures/7fbe448c-5...,11206.0,2.0,2.0
74109,17045948,5.273000,Apartment,Entire home/apt,"{TV,""Wireless Internet"",""Air conditioning"",Kit...",2,1.0,Real Bed,strict,True,...,40.738535,-74.000157,Designer's Apartment in HEART of NYC,West Village,0,NaN,https://a0.muscache.com/im/pictures/b3971b63-0...,10011,0.0,2.0
74110,3534845,4.852030,Boat,Entire home/apt,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",4,1.0,Real Bed,moderate,False,...,33.761096,-118.192409,Cozy Boat at Shoreline Village,Long Beach,205,96.0,https://a0.muscache.com/im/pictures/22968537/d...,90802,1.0,2.0

In [3]:
df.columns

Index(['id', 'log_price', 'property_type', 'room_type', 'amenities',
       'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy',
       'cleaning_fee', 'city', 'description', 'first_review',
       'host_has_profile_pic', 'host_identity_verified', 'host_response_rate',
       'host_since', 'instant_bookable', 'last_review', 'latitude',
       'longitude', 'name', 'neighbourhood', 'number_of_reviews',
       'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds'],
      dtype='object')

In [4]:
df = df.drop(columns=["id","amenities","description","first_review","last_review","latitude","longitude","thumbnail_url"])
df

,log_price,property_type,room_type,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_has_profile_pic,...,host_response_rate,host_since,instant_bookable,name,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5.010635,Apartment,Entire home/apt,3,1.0,Real Bed,strict,True,NYC,t,...,NaN,2012-03-26,f,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,11201,1.0,1.0
1,5.129899,Apartment,Entire home/apt,7,1.0,Real Bed,strict,True,NYC,t,...,100%,2017-06-19,t,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,10019,3.0,3.0
2,4.976734,Apartment,Entire home/apt,5,1.0,Real Bed,moderate,True,NYC,t,...,100%,2016-10-25,t,The Garden Oasis,Harlem,10,92.0,10027,1.0,3.0
3,6.620073,House,Entire home/apt,4,1.0,Real Bed,flexible,True,SF,t,...,NaN,2015-04-19,f,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,94117.0,2.0,2.0
4,4.744932,Apartment,Entire home/apt,2,1.0,Real Bed,moderate,True,DC,t,...,100%,2015-03-01,t,Great studio in midtown DC,Columbia Heights,4,40.0,20009,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,4.605170,Apartment,Private room,1,1.0,Real Bed,flexible,False,NYC,t,...,NaN,2013-03-24,f,one room bushwick,Williamsburg,0,NaN,11206.0,1.0,1.0
74107,5.043425,Apartment,Entire home/apt,4,2.0,Real Bed,moderate,True,LA,t,...,100%,2016-05-03,f,Spacious Hermosa 2 BR on PCH,Hermosa Beach,16,93.0,90254,2.0,4.0
74108,5.220356,Apartment,Entire home/apt,5,1.0,Real Bed,moderate,True,NYC,t,...,100%,2012-01-05,t,Modern 2 Bedroom Apartment in Williamsburg,Williamsburg,43,94.0,11206.0,2.0,2.0
74109,5.273000,Apartment,Entire home/apt,2,1.0,Real Bed,strict,True,NYC,t,...,100%,2017-09-17,t,Designer's Apartment in HEART of NYC,West Village,0,NaN,10011,0.0,2.0
74110,4.852030,Boat,Entire home/apt,4,1.0,Real Bed,moderate,False,LA,t,...,100%,2012-11-26,f,Cozy Boat at Shoreline Village,Long Beach,205,96.0,90802,1.0,2.0

In [5]:
df.isna().sum()

log_price                     0
property_type                 0
room_type                     0
accommodates                  0
bathrooms                   200
bed_type                      0
cancellation_policy           0
cleaning_fee                  0
city                          0
host_has_profile_pic        188
host_identity_verified      188
host_response_rate        18299
host_since                  188
instant_bookable              0
name                          0
neighbourhood              6872
number_of_reviews             0
review_scores_rating      16722
zipcode                     966
bedrooms                     91
beds                        131
dtype: int64

In [6]:
df.dtypes

log_price                 float64
property_type              object
room_type                  object
accommodates                int64
bathrooms                 float64
bed_type                   object
cancellation_policy        object
cleaning_fee                 bool
city                       object
host_has_profile_pic       object
host_identity_verified     object
host_response_rate         object
host_since                 object
instant_bookable           object
name                       object
neighbourhood              object
number_of_reviews           int64
review_scores_rating      float64
zipcode                    object
bedrooms                  float64
beds                      float64
dtype: object

In [7]:

df["host_has_profile_pic"] = df["host_has_profile_pic"].fillna(df["host_has_profile_pic"].mode()[0])
df["host_identity_verified"] = df["host_identity_verified"].fillna(df["host_identity_verified"].mode()[0])
df["host_response_rate"] = df["host_response_rate"].fillna(df["host_response_rate"].mode()[0])

from datetime import datetime

df['host_since'] = pandas.to_datetime(df['host_since'])
df['host_experience'] = (datetime.now() - df['host_since']).dt.days // 365
df['host_experience'] = df['host_experience'].fillna(df['host_experience'].median())
df = df.drop('host_since', axis=1) 

cat_cols = ['neighbourhood', 'zipcode']
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

num_cols = ['bathrooms', 'bedrooms', 'beds', 'review_scores_rating']
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

In [8]:
df.isna().sum()

log_price                 0
property_type             0
room_type                 0
accommodates              0
bathrooms                 0
bed_type                  0
cancellation_policy       0
cleaning_fee              0
city                      0
host_has_profile_pic      0
host_identity_verified    0
host_response_rate        0
instant_bookable          0
name                      0
neighbourhood             0
number_of_reviews         0
review_scores_rating      0
zipcode                   0
bedrooms                  0
beds                      0
host_experience           0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in df.columns:
    if df[i].dtype == "object":
        df[i] = le.fit_transform(df[i].astype(str))

In [10]:
df.dtypes

log_price                 float64
property_type               int64
room_type                   int64
accommodates                int64
bathrooms                 float64
bed_type                    int64
cancellation_policy         int64
cleaning_fee                 bool
city                        int64
host_has_profile_pic        int64
host_identity_verified      int64
host_response_rate          int64
instant_bookable            int64
name                        int64
neighbourhood               int64
number_of_reviews           int64
review_scores_rating      float64
zipcode                     int64
bedrooms                  float64
beds                      float64
host_experience           float64
dtype: object

In [11]:
# now spliting the data into input and output variables
y = df["log_price"]
X = df.drop(columns=["log_price"], axis=1)
X

,property_type,room_type,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,host_has_profile_pic,host_identity_verified,host_response_rate,instant_bookable,name,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds,host_experience
0,0,0,3,1.0,4,2,True,4,1,1,2,0,10464,77,2,100.000000,195,1.0,1.0,13.0
1,0,0,7,1.0,4,2,True,4,1,0,2,1,65672,252,6,93.000000,74,3.0,3.0,8.0
2,0,0,5,1.0,4,1,True,4,1,1,2,1,66396,247,10,92.000000,84,1.0,3.0,9.0
3,17,0,4,1.0,4,0,True,5,1,1,2,0,9387,325,0,94.067365,748,2.0,2.0,10.0
4,0,0,2,1.0,4,1,True,2,1,1,2,1,32068,119,4,40.000000,341,0.0,1.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74106,0,1,1,1.0,4,0,False,4,1,1,2,0,72348,605,0,94.067365,203,1.0,1.0,12.0
74107,0,0,4,2.0,4,1,True,3,1,0,2,0,59902,255,16,93.000000,515,2.0,4.0,9.0
74108,0,0,5,1.0,4,1,True,4,1,1,2,1,43692,605,43,94.000000,203,2.0,2.0,13.0
74109,0,0,2,1.0,4,2,True,4,1,0,2,1,26450,592,0,94.067365,61,0.0,2.0,8.0
74110,2,0,4,1.0,4,1,False,3,1,1,2,0,22195,319,205,96.000000,577,1.0,2.0,13.0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr = lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred

array([4.98393832, 6.38814297, 5.59194163, ..., 5.37132436, 4.35297864,
       5.07070991], shape=(22234,))

In [15]:
y_test

2208     5.164786
38204    6.380123
67992    5.192957
14444    3.912023
43112    4.248495
           ...
43387    4.553877
54975    4.941642
59052    6.109248
56143    4.553877
8201     5.393628
Name: log_price, Length: 22234, dtype: float64

In [16]:
print(lr.coef_)
print(lr.intercept_)

[ 0.00828423 -0.33811095  0.19220666  0.0883374  -0.00089029 -0.00214487
 -0.03225541  0.07496755 -0.00672435 -0.02071734 -0.0146752  -0.01433155
  0.0054608   0.02896526 -0.02593169  0.04158108 -0.04126554  0.12759301
 -0.06808741  0.03378543]
4.7825283838838475

In [17]:
from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y_test, y_pred))

0.07846257050882996

In [18]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.5293067341016646